### ISSUE TITLE
How can I use a date parameter for UNTIL within RRULE ?

### ISSUE THREAD

**Issue by mariegendron** [tplaner/When#27]
I don't know how to use a date parameter for UNTIL ?

RRULE:FREQ=YEARLY;UNTIL=20000131T090000Z

And what means the letter Z at the end ?

Your code sounds really great !
I just need to try it more !

**Comment by Alexwijn** [comment]
Year: 2000
Month: 01
Day: 31
Hour: 09
Minute: 00
Seconds: 00
Timezone: Zulu (UTC/GMT)

**Comment by tplaner** [comment]
The date is in [ISO 8601](http://en.wikipedia.org/wiki/ISO_8601) format.
