### ISSUE TITLE
Logic error when trying to create weekly recurrences with a byDay before the current start date day

### ISSUE THREAD

**Issue by NetbearSoftware** [tplaner/When#29]
Hello Tom,

Firstly, thank-you for this great library! It is really amazing!

I've come across an error when I try and create weekly recurrences that have a `BYDAY` value before the day of the start date.

For example, if I try and generate recurrences with the following rule and a start date day of Wednesday, I get an exception `The start date must be the first occurrence`.

```
FREQ=WEEKLY;BYDAY=Mo;COUNT=4;
```
If I change `BYDAY` to `We`, `Th`, `Fr`, `Sa` or `Su` it works correctly.

Is there anyway that When can deal with this sort of scenario and continue to create the event on the following Monday?

Tim

**Comment by tplaner** [comment]
Hey Tim,

The start date actually has to match the rules which you specify (it is the first occurrence). Therefore if you're attempting to generate occurrences which are on a Monday, the start date needs to be a Monday.

Here is a working example of your `rrule`.

```
$when = new When();
$when->startDate(new DateTime('2015-02-02'))
     ->rrule('FREQ=WEEKLY;BYDAY=MO;COUNT=4;')
     ->generateOccurrences();

echo '<pre>';
print_r($when->occurrences);
echo '</pre>';
```

**Comment by NetbearSoftware** [comment]
Hi Tom,

Thank-you for getting back to me! I had feared that this was the case.

Can you think of any creative way for me to deal with the scenario of someone who wants an event to happen every monday, wednesday and friday but the first event occurs on a Friday?

Thanks for your help,
Tim

**Comment by tplaner** [comment]
That is perfectly valid, try this:

```
$when->startDate(new DateTime('2015-02-06'))
     ->rrule('FREQ=WEEKLY;BYDAY=MO,WE,FR;COUNT=4;')
     ->generateOccurrences();
```

**Comment by NetbearSoftware** [comment]
Hi Tom,

Well I'm feeling a little silly now, I can't reproduce it even with the rules which I noted didn't work correctly for me.

The only thing I can think of is that my start date conversion may have been faulty (I'm converting between timezones) and wasn't actually a day on which a repeat was being specified for.

Sorry about that, but thank-you very much for your assistance.

Tim

**Comment by rahul7156** [comment]
I also suffering from same issue plz give me any suggestion 
<pre>Exception &#039;app\components\**InvalidStartDate** &#039; with message &#039;**The start date must be the first occurrence**.&#039
