### ISSUE TITLE
return human readable rrule 

### ISSUE THREAD

**Issue by mteichtahl** [tplaner/When#33]
Id like to make a feature request. When providing a rrule, would it be possible to also make a human readable form available? Perhaps a toRruleAString method?

**Comment by tplaner** [comment]
Good idea.

I have some ideas on how to do this fairly easily, I'll look into it.

**Comment by AdamEsterle** [comment]
I would love this too

This package does it
https://github.com/rlanvin/php-rrule

More specifically
https://github.com/rlanvin/php-rrule/blob/master/src/i18n/en.php
