### ISSUE TITLE
Why is there an InvalidStartDate error?

### ISSUE THREAD

**Issue by vz28bh** [tplaner/When#38]
It seems there is an unneeded error being thrown if the start day does not match one of the recurring days. For example if I create an event on Monday and say it is weekly recurring on Sunday and Monday, an error is thrown. This is a perfectly normal situation so I commented out the "throw new InvalidStartDate()" and it works correctly, but I am concerned that there may be a reason for the that I am unaware of. Is there a specific reason for this error?

Thanks, this is a very nice little library.

**Comment by gsidler** [comment]
There are some cases where you want to be sure that the start date is the first occurrence of the series. Consider for example this rule: "FREQ=YEARLY;BYMONTH=2;" If the start date is not a date within the month of February, then this rule will not return any occurrances.

**Comment by tplaner** [comment]
According to the iCalendar specification [RFC5545](http://tools.ietf.org/html/rfc5545):

> The COUNT rule part defines the number of occurrences at which to
> range-bound the recurrence.  The "DTSTART" property value always
> counts as the first occurrence.

I interpreted this as the first date must also be an occurrence, though reading the statement again now, it doesn't specifically state that, it only says that it must be counted as the first.

I think that this is still worth throwing an exception over, you can always choose to ignore it.

**Comment by vz28bh** [comment]
Maybe a friendlier solution would be to take the start date as the first "possible" start date and the actual first event would be the first valid event date after the given start date.

**Comment by milokmet** [comment]
What about some parameter RFC5545_COMPLIANT that will turn on/off the exception? It would be very handy to have a method for find the next occurence of rule relative to a specified date without throwing an exception.

**Comment by kcrawley** [comment]
@tplaner I've submitted a PR that would address some of the concerns here while remaining backwards compatible for those who have implemented the library as-is. I've taken the recommendations of @milokmet and introduced a small change alongside unit tests to cover the changes.

Thank you! Have a Merry Christmas! :)

**Comment by kcrawley** [comment]
@tplaner thank you. would it be possible to get an updated tag?

**Comment by AdamEsterle** [comment]
@tplaner could there be a tag with this commit in it?

**Comment by jmarikle** [comment]
@tplaner I too would like to see this included as an option.  It'll save me the need to add in a check to set the start date as a valid occurrence if I just want a general start date outside of the occurrence parameters.
