### ISSUE TITLE
(Unwanted) Extra occurrence on weekly intervals if startDate matches weekStart 

### ISSUE THREAD

**Issue by mhnrm** [tplaner/When#45]
I'm trying to generate events that occur every 2 (or more) weeks using interval:

``` php
        $startDate = new \DateTime('2015-10-26');
        $endDate = new \DateTime('2016-01-31');

        $eventGenerator = new When();
        $eventGenerator->startDate($startDate);
        $eventGenerator->until($endDate);

        $eventGenerator->freq('weekly');
        $eventGenerator->interval(2);

        $eventGenerator->generateOccurrences();

        var_dump($eventGenerator->occurrences);
```

But the first three events are recurred weekly, before the interval is working as expected:

``` php
array (size=8)
  0 => 
    object(DateTime)[994]
      public 'date' => string '2015-10-26 00:00:00.000000' (length=26)
      public 'timezone_type' => int 3
      public 'timezone' => string 'Europe/Berlin' (length=13)
  1 => 
    object(DateTime)[996]
      public 'date' => string '2015-11-02 00:00:00.000000' (length=26)
      public 'timezone_type' => int 3
      public 'timezone' => string 'Europe/Berlin' (length=13)
  2 => 
    object(DateTime)[993]
      public 'date' => string '2015-11-09 00:00:00.000000' (length=26)
      public 'timezone_type' => int 3
      public 'timezone' => string 'Europe/Berlin' (length=13)
  3 => 
    object(DateTime)[997]
      public 'date' => string '2015-11-23 00:00:00.000000' (length=26)
      public 'timezone_type' => int 3
      public 'timezone' => string 'Europe/Berlin' (length=13)
  4 => 
    object(DateTime)[998]
      public 'date' => string '2015-12-07 00:00:00.000000' (length=26)
      public 'timezone_type' => int 3
      public 'timezone' => string 'Europe/Berlin' (length=13)
  5 => 
    object(DateTime)[999]
      public 'date' => string '2015-12-21 00:00:00.000000' (length=26)
      public 'timezone_type' => int 3
      public 'timezone' => string 'Europe/Berlin' (length=13)
  6 => 
    object(DateTime)[1000]
      public 'date' => string '2016-01-04 00:00:00.000000' (length=26)
      public 'timezone_type' => int 3
      public 'timezone' => string 'Europe/Berlin' (length=13)
  7 => 
    object(DateTime)[1001]
      public 'date' => string '2016-01-18 00:00:00.000000' (length=26)
      public 'timezone_type' => int 3
      public 'timezone' => string 'Europe/Berlin' (length=13)
```

If I set the interval to 3, I get a 1-week and a 2-week interval before 3-week intervals are computed:

``` php
array (size=6)
  0 => 
    object(DateTime)[994]
      public 'date' => string '2015-10-26 00:00:00.000000' (length=26)
      public 'timezone_type' => int 3
      public 'timezone' => string 'Europe/Berlin' (length=13)
  1 => 
    object(DateTime)[996]
      public 'date' => string '2015-11-02 00:00:00.000000' (length=26)
      public 'timezone_type' => int 3
      public 'timezone' => string 'Europe/Berlin' (length=13)
  2 => 
    object(DateTime)[993]
      public 'date' => string '2015-11-16 00:00:00.000000' (length=26)
      public 'timezone_type' => int 3
      public 'timezone' => string 'Europe/Berlin' (length=13)
  3 => 
    object(DateTime)[997]
      public 'date' => string '2015-12-07 00:00:00.000000' (length=26)
      public 'timezone_type' => int 3
      public 'timezone' => string 'Europe/Berlin' (length=13)
  4 => 
    object(DateTime)[998]
      public 'date' => string '2015-12-28 00:00:00.000000' (length=26)
      public 'timezone_type' => int 3
      public 'timezone' => string 'Europe/Berlin' (length=13)
  5 => 
    object(DateTime)[999]
      public 'date' => string '2016-01-18 00:00:00.000000' (length=26)
      public 'timezone_type' => int 3
      public 'timezone' => string 'Europe/Berlin' (length=13)
```

Funny enough, this only happens if the start date is a monday - for any other start date, the interval is working as expected (startdate="2015-10-25", interval=3):

``` php
array (size=5)
  0 => 
    object(DateTime)[994]
      public 'date' => string '2015-10-25 00:00:00.000000' (length=26)
      public 'timezone_type' => int 3
      public 'timezone' => string 'Europe/Berlin' (length=13)
  1 => 
    object(DateTime)[993]
      public 'date' => string '2015-11-15 00:00:00.000000' (length=26)
      public 'timezone_type' => int 3
      public 'timezone' => string 'Europe/Berlin' (length=13)
  2 => 
    object(DateTime)[996]
      public 'date' => string '2015-12-06 00:00:00.000000' (length=26)
      public 'timezone_type' => int 3
      public 'timezone' => string 'Europe/Berlin' (length=13)
  3 => 
    object(DateTime)[997]
      public 'date' => string '2015-12-27 00:00:00.000000' (length=26)
      public 'timezone_type' => int 3
      public 'timezone' => string 'Europe/Berlin' (length=13)
  4 => 
    object(DateTime)[998]
      public 'date' => string '2016-01-17 00:00:00.000000' (length=26)
      public 'timezone_type' => int 3
      public 'timezone' => string 'Europe/Berlin' (length=13)
```

It seems that When() just doesn't like mondays...

I suspect that it may have something to do with l.550 of When(), the block that is commented with 

``` php
// not very happy with this
```

Could you please have a look into this?

best regards,
µ.

**Comment by tplaner** [comment]
Hey @mhnrm,

For some reason I made the default day of the week if you don't set one Monday. Given this everything is working properly, though the results are confusing if you expect the week to start on a Sunday.

I'm going to change the default week start day to "Sunday", however in the meantime you can get the expected results by simply adding `$eventGenerator->wkst('SU');`, it won't hurt anything to have this explicitly assigned.

Best,

Tom

**Comment by mhnrm** [comment]
Hi Tom,

thank you very much for your answer! So that's what `$wkst` means... well, for me, as I'm living in Germany, I totally ok with Monday being the week start on Monday.

But I can't see how that solves my problem described above. I admit that I posted a serious amount of code and it may be hard to oversee, so please allow me to repeat my results shortened here:

### Given:  
```php
$startDate = 2015-10-26 (a Monday), $freq = weekly, interval = 2;
```

### Expected: 
* 2015-10-26
* 2015-11-09
* 2015-11-23
* 2015-12-07
* ...

### I get:
* 2015-10-26
* *2015-11-02*
* 2015-11-09
* 2015-11-23
* 2015-12-07
* ...

i.e. an extra event that desn't follow the 2-week interval. It's even worse for intervals of 3 or more weeks - there are always two "misplaced" events before the interval works as expected. And - this happens only for events on Mondays; when I set the start day to any other day of the week, everything works fine.

best regards,
µ.

**Comment by mhnrm** [comment]
Hi,

after some more playing around with this issue, I have to slightly correct the description:

* It's not related to mondays, but happens every time the start date matches the week start day ```$wkst```
* In these cases, an extra occurrence for the next week after the start date is generated
* all other occurences are computed correctly 
* i.e. there is a 1-week and a (n-1)-week interval for the first weeks

Investigating a little further, it seems to me that you 

* first add the start date to the occurrences list
* run through the next 7+1 days (why?), getting the next week recurrence of the day
* which is then added to the list, as occursOn() doesn't care for the interval

So I was able to fix the issue by just removing the '+1'  in line 556:

```php
                if ($count === 0)
                {
                    $startWeekDay = clone $this->startDate;
                    $startWeekDay->modify("next " . $wkst);

                    $daysLeft = $dateLooper->diff($startWeekDay)->format("%a");

                    $startWeekDay->modify("last " . $wkst);
                }
```

But as I'm still not completely grokking what your intention was in that loop, I'm not sure if this won't break any other stuff.

Could you please have another look on that part of the code?

best regards,
µ.

**Comment by tplaner** [comment]
Was looking into it yesterday and I'm still trying to figure out a solution. I'll definitely let you know when I do.

**Comment by mhnrm** [comment]
I was finally able to nail down the issue to occur under the following circumstances:
- WeekStart matches first occurrence
- Time is exactly 00:00:00

Fixed on PR: https://github.com/tplaner/When/pull/52
