### ISSUE TITLE
Whole Year Skipped for monthly recurring.

### ISSUE THREAD

**Issue by pankajmishra15** [tplaner/When#48]
if you set monthly recurring for Dec 5 2015. Which's End Date is Dec 5 2025. Event should display in All Month's 5th Date. it's not being display in any month of 2016 and re-appearing from 5-Jan-2017.

It's happening for November also. This time Event is skipped in 2018 and so on.
Can any body help on this? Waiting for your positive response.

**Comment by petski** [comment]
Couldn't reproduce with the latest version of When and this code-snippet:

```php
$r = new When();
$r->startDate(new DateTime("2015-12-05 09:00:00"))->rrule("FREQ=MONTHLY");
$r->generateOccurrences();
print_r($r->getOccurrencesBetween(new DateTime('2015-12-05 09:00:00'), new DateTime('2025-12-05 09:00:00')));
```
@PANKAJ153 Please supply a code-snippet that reproduces this issue.
