### ISSUE TITLE
Make it possible to use other time objects than \DateTime

### ISSUE THREAD

**Issue by burzum** [tplaner/When#51]
The lib has hard dependencies on a few base classes:

``` php
$this->until(new \DateTime($param));
$this->until->add(new \DateInterval('P400Y'));
```

It should be possible to change them. Either by providing a method than can be overloaded or a getter and setter that will allow me to define the interval and date objects.

Calling the classes directly in the code makes it impossible to work with custom date objects.

**Comment by tplaner** [comment]
Good idea, will take this into consideration for a future rewrite.
