### ISSUE TITLE
Support for DTEND

### ISSUE THREAD

**Issue by Blindmikey** [tplaner/When#56]
Is there support for ( or planned for ) DTEND? 

eg) 11th of the month - 13th every month for 4 months

Would be:

```
DTSTART:20160511T000000
DTEND:20160513T000000
RRULE:FREQ=MONTHLY;BYMONTHDAY=11;INTERVAL=1;COUNT=4
```

But I can't find where I can establish a DTEND in this class. 

Any help is greatly appreciated, very handy class.

Best,
-M

**Comment by tplaner** [comment]
Unfortunately there is no information regarding how DTEND is supposed to interact with RRULE. If you know of how other libraries handle this or can find a specification it could be considered for future versions.
