### ISSUE TITLE
Does not work properly when event is on 31th and Occorance is monthly

### ISSUE THREAD

**Issue by perochak** [tplaner/When#61]
When we have an event on 31th of December then it does not generate the next event on month when the day is less then 31 i.e. when days in month are 30 or less.

$r = new When();
$r->startDate(new DateTime("2015-12-31 01:00:00"))
  ->freq("monthly")
  ->count(30)
  ->generateOccurrences();

**Comment by perochak** [comment]
Managed modifying code at line 710 as below

`if ($this->occursOn($dateLooper))
                    {
                        $occurrences = array_merge($occurrences, $this->generateTimeOccurrences($dateLooper));
                    }elseif($day==$days){
                        $occurrences = array_merge($occurrences, $this->generateTimeOccurrences($dateLooper));
                    }`

**Comment by tplaner** [comment]
This is actually working as intended (and according to the spec).

You're looking for:
```
$r = new When();
$r->startDate(new DateTime("2015-12-31 01:00:00"))
->freq("monthly")
->count(30)
->bymonthday(-1)
->generateOccurrences();
```
The above statement specifically says you're looking for the last day of the month, whereas the initial statement will only match recurrences which are on the 31st day of the month.

**Comment by perochak** [comment]
You are right.

**Comment by perochak** [comment]
What about when we want to generate the event dates when we have a start and end date?
