### ISSUE TITLE
Documentation does not match the version

### ISSUE THREAD

**Issue by jacobdo** [tplaner/When#63]
The documentation displayed on the front page does not seem to match the contents of the package i.e. it says that you can use getOccurrencesBetween in 2.0, however, when you install it, the library does not contain this method.

**Comment by djamestaft** [comment]
Hey jacobdo,

I have used this method with version 2.0 of tplaner/when.
Here is a screenshot of the method declaration in the source.
![screen shot 2017-02-28 at 14 07 14](https://cloud.githubusercontent.com/assets/11571550/23404789/22910752-fdb7-11e6-91ad-d3514793e70a.png)

Are you using the method properly? Or maybe something went wrong when you installed the library perhaps?

Are you using composer to install the library?

**Comment by jacobdo** [comment]
Yes, I install it via composer:

composer require tplaner/when

In the composer.json it says:

"tplaner/when": "^2.0" (also tried "tplaner/when": "2.*" to no avail)

I have looked through the When.php, the version I have installed is missing getOccurrencesBetween along with bunch of other methods that the master has.

**Comment by tplaner** [comment]
Modify your `composer.json` and change it to "tplaner/when": "dev-master", then do a `composer install`.

**Comment by djamestaft** [comment]
jacobdo, that is strange because that is how my composer.json file looks as well.

![screen shot 2017-02-28 at 16 25 53](https://cloud.githubusercontent.com/assets/11571550/23409059/807c802c-fdca-11e6-9473-f832d1b67ee1.png)

Did you run a composer update or anything after editing your composer.json file?

**Comment by djamestaft** [comment]
Maybe re-run composer update

**Comment by jacobdo** [comment]
Thanks @djamestaft and @tplaner, but when running "dev-master", should I not worry that things might stop working if you decide to deprecate something?

**Comment by tplaner** [comment]
For now I believe you can do `"dev-master#7f94f03"` to lock in the latest release. I'll try to push up a new tag later tonight.

**Comment by jacobdo** [comment]
@tplaner Thanks, that does the trick

**Comment by piernik** [comment]
The same here - could be fixed after 4 months ;)
