### ISSUE TITLE
Can't traverse year boundary using WEEKLY interval

### ISSUE THREAD

**Issue by chriskot870** [tplaner/When#68]
I create a When object and set the recur date to a date in 2017 and define a repetition rule with a Weekly interval and then cycle through getting the next date in the cycle. When I go past the new year it fails.

$begdatetime is a PHP DateTime structure whose date is:
date - "2017-08-24 08:00:00.000000"
timezone - "America/Chicago"
$reprule - "FREQ=WEEKLY;INTERVAL=1;BYDAY=SU"

        $when = new When();
        $when->recur($begdatetime)->rrule($reprule);
        while ( $nxtdatetime = $when->next()) {
             <unimportant code that breaks on a condition after the next would go into 2018>
        }

The error is:
PHP Fatal error:  Uncaught Exception: DateTime::__construct(): Failed to parse time string (2017-13-1 08:00:00) at position 6 (3): Unexpected character in /usr/share/php/when/When.php:561
Stack trace:
#0 /usr/share/php/when/When.php(561): DateTime->__construct('2017-13-1 08:00...')
#1 /usr/share/php/when/When.php(719): When->create_suggestions()
#2 /var/www/html/mhscheduler/mhscheduler_lib.php(3327): When->next()
#3 /var/www/html/mhscheduler/mhscheduler_lib.php(3251): Schedule->nextoccurrence()
#4 /var/www/html/mhscheduler/mhscheduler_lib.php(344): Schedule->nexteventdatetime()
#5 /var/www/html/mhscheduler/doscheduling.php(227): scheduleevent(Object(Account), Object(Schedule))
#6 {main}
  thrown in /usr/share/php/when/When.php on line 561

Clearly it's a year roll over issue as there are not 13 months in 2017. Here is the cuplrit:

	554				if($_day <= $days_in_month)
	555			        {
	556					$tmp_date = new DateTime($year . '-' . $month . '-' . $_day . ' ' . $timestamp);
	557				}
	558				else
	559				{
	560					$tmp_month = $month+1;
	561					$tmp_date = new DateTime($year . '-' . $tmp_month . '-' . $overflow_count . ' ' . $timestamp);
	562					$overflow_count++;
	563				}
	564				
	565				$week_day = $tmp_date->format('w');

When I get to line 560 when $month = 12, $tmp_month gets set to 13 and that is used to determine the month. PHP's DateTime __construct chokes on that. Clearly when $month is 12 $tmp_month should go to 1 and $year or some variation of it should be incremented.

I am just not sure of the fix. Don't know if it's as simple as:

if ($month == 12 ) {
    $tmp_month = 1;
    $year++;
} else {
    $tmp_month = month +1;
}

Not sure it's that simple as I haven't had time to look at how all the incrementing gets done, what all the $tmp_* are about. I don't want to fix one problem and create another.

Anyone seen this before and is there a fix ?

I am running on Fedora25 and have this RPM installed:

$ rpm -qi php-when
Name        : php-when
Version     : 0.3
Release     : 7.fc24
Architecture: noarch
Install Date: Wed 15 Feb 2017 09:19:50 PM CST
Group       : Unspecified
Size        : 22604
License     : MIT
Signature   : RSA/SHA256, Thu 31 Mar 2016 06:45:46 PM CDT, Key ID 4089d8f2fdb19c98
Source RPM  : php-when-0.3-7.fc24.src.rpm
Build Date  : Thu 04 Feb 2016 06:49:53 PM CST
Build Host  : bvirthost02-nfs.phx2.fedoraproject.org
Relocations : (not relocatable)
Packager    : Fedora Project
Vendor      : Fedora Project
URL         : https://github.com/tplaner/When
Summary     : Date/Calendar recursion library for PHP
Description :
PHP library that handles recursive dates: It determines the next date of
recursion given an iCalendar "rrule" like pattern.

**Comment by chriskot870** [comment]
I checked out the git repository (git clone https://github.com/tplaner/When)  and see that  my version 0.3 is very old. Looks like it is up to 2.X now so I'll give that a try. I see one of the weekly tests does go over the year boundary so I assume that passed and my problem will be resolved with the new version.

**Comment by tplaner** [comment]
Should definitely be resolved in a newer version.
