### ISSUE TITLE
New version code

### ISSUE THREAD

**Issue by tmblog** [tplaner/When#70]
Hello there thank you for the nice library very handy. As there isn't any documentation can you please help me convert this (found on Stackoverflow) to the new version so it works.

`$r = new When();`
 `$r->recur(<start date here>, 'weekly')`
  `->until(<end date here>)`
  `->wkst('SU')`
  `->byday(array('MO', 'TU', 'WE', 'TH', 'FR'));`

`while($result = $r->next())`
`{`
   ` echo $result->format('c') . '<br />';`
`}`

And what format does the date need to be in?

**Comment by tplaner** [comment]
Something like this:
```
$r = new When();
$r->startDate(new DateTime('20181203T090000'))
  ->freq('weekly')
  ->wkst('SU')
  ->byday(['MO', 'TU', 'WE', 'TH', 'FR'])
  ->generateOccurrences();

print_r($r->occurrences);
```
The `startDate` should be a [`DateTime`](http://php.net/manual/en/class.datetime.php) and it also should be the first occurrence of the set.

**Comment by tmblog** [comment]
Thank you for the response just a question is there a way to format the output as in the old way, because occurrences doesn't have format anymore.

`$result->format('c')`

Thanks again.

**Comment by tplaner** [comment]
The occurrences are just [`DateTime`](http://php.net/manual/en/class.datetime.php) objects, so if you loop over them you can format them however you want:

```
foreach($r->occurrences as $occurrence) {
    echo $occurrence->format('c');
}
```

**Comment by tmblog** [comment]
Thanks so much for your help I really appreciate it!
I am using:
`getOccurrencesBetween(new DateTime('2018-12-01 09:00:00'), new DateTime('2019-01-30 09:00:00'))`
To set a start and end date. This way the start date gets ignored and the `startDate()` overrides it.

Is there a reason to add two dates in `getOccurrencesBetween()` if it gets ignored?

perhaps there's another way to set an end date?

Thanks again.

**Comment by shaunmilo** [comment]
For anyone that comes across this like I did, my solution to the above PHP fatal error was to make sure the BYDAY included ALL days of the week (Sunday - Saturday) as opposed to just Monday - Friday.

**Comment by tplaner** [comment]
Unfortunately, this has turned into a more generalized programming issue with validation and normalization of input.

If you have a question specific to When feel free to open a new issue.
