### ISSUE TITLE
Getting the next occurance or rule from NOW

### ISSUE THREAD

**Issue by bobemoe** [tplaner/When#77]
The start date must be the first occurrence. So given a specific rule, say: `FREQ=MONTHLY;BYDAY=FR;BYMONTHDAY=13` how would I calculate the next occurrence after NOW? 

I've tried: `$r->RFC5545_COMPLIANT = When::IGNORE;` but this just gives an empty array, as expected I think.

This looks interesting https://github.com/tplaner/When/pull/19 but I cant get it to work, even after calling adjustStartDate() I still get the `The start date must be the first occurrence` exception.

Is this possible? I'm planning on using this to calculate when a specific rule would occur next (relative to today/now) without knowing any occurrences.

Ideas? Thanks.

**Comment by boryn** [comment]
Hi @bobemoe, I have just tried and it works perfectly as expected:

```php
$r = new When();
$r->RFC5545_COMPLIANT = When::IGNORE;
$r->startDate(new \DateTime())
  ->count(1)
  ->rrule("FREQ=MONTHLY;BYDAY=FR;BYMONTHDAY=13")
  ->generateOccurrences();

return $r->occurrences;
```

**Comment by bobemoe** [comment]
@boryn thanks for this.  I'm no longer working on this project so have no way to confirm it solves my original issue.

But if you've tested it (and assuming it wasn't friday the 13th when you did the test) I'd be happy for you to close the issue.

thanks :)

**Comment by boryn** [comment]
Yeah, you asked this two years ago and I just started using the library two days ago :)
