### ISSUE TITLE
Support for PHP 5.6

### ISSUE THREAD

**Issue by skylerkatz** [tplaner/When#78]
Hi @tplaner,

I was wondering if you would be open to a PR that adds support for PHP 5.6 to the repository. The only change needed is moving the PHPUnit constraint to `5.7.27`. In my own fork of the package all of the tests continue to pass.

I know that in the commit https://github.com/tplaner/When/commit/160e98f3d1ed6a824bdfaa2ede211d1877e8e5ce you dropped support for 5.x to allow for 7.x enhancements, but you are not currently using any 7.x exclusive features.

Thanks for your consideration!

**Comment by tplaner** [comment]
Sounds good, would merge.
