### ISSUE TITLE
FREQ=MONTHLY;UNTIL not working

### ISSUE THREAD

**Issue by truecastdesign** [tplaner/When#79]
With a starting date of 2020-11-24T10:00:00-08:00

and

FREQ=MONTHLY;UNTIL=20210129T075959Z

I get these 3 dates. Not correct. It should output 2020-11-24,  2020-12-24, and  2021-01-24

[1] => stdClass Object
        (
            [description] => This is the desc for the repeating event.
            [location] => 
            [status] => confirmed
            [summary] => Repeating Event Tuesday
            [start] => 2021-01-24 10:00:00
            [end] => 2021-01-24 10:30:00
        )

    [2] => stdClass Object
        (
            [description] => This is the desc for the repeating event.
            [location] => 
            [status] => confirmed
            [summary] => Repeating Event Tuesday
            [start] => 2021-01-24 10:00:00
            [end] => 2021-01-24 10:30:00
        )

    [3] => stdClass Object
        (
            [description] => This is the desc for the repeating event.
            [location] => 
            [status] => confirmed
            [summary] => Repeating Event Tuesday
            [start] => 2021-01-24 10:00:00
            [end] => 2021-01-24 10:30:00
        )

**Comment by boryn** [comment]
Hi @truecastdesign, I have just tried version 3.1 with this code:

```php
$r = new When();
$r->startDate(new \DateTime("2020-11-24T10:00:00-08:00"))
  ->rrule("FREQ=MONTHLY;UNTIL=20210129T075959Z")
  ->generateOccurrences();

return $r->occurrences;
```

and this produced the expected `2020-11-24`, `2020-12-24`, `2021-01-24`.
