### ISSUE TITLE
Updated Instructions ? 

### ISSUE THREAD

**Issue by marcoczen** [tplaner/When#82]
Hi,

This project is active as you just did an update 40+ minutes ago.
So is there updated instructions ? or wiki ? or tutorial that explains how to use this library ?

This library seems to be the simplest as there are only 2 php files, When.php and Valid.php .
Requiring these 2 files will be sufficient yes ? I have a legacy code that i need to maintain and 
composer support seems wonky ...

**Comment by tplaner** [comment]
I cleaned up the repo today pending a potential larger rewrite of the library which I've been working on off and on for a long time now.

Documentation is not really needed as the tests demonstrate basically everything that the library is capable of. The easiest way to start using the library is to utilize rrule's themselves:

```
$r = new When();
$r->startDate(new DateTime("19980213T090000"))
  ->rrule("FREQ=MONTHLY;BYDAY=FR;BYMONTHDAY=13")
  ->generateOccurrences();

print_r($r->occurrences);
```

**Comment by marcoczen** [comment]
Thank you.
So https://github.com/tplaner/When/blob/master/tests/ is my reference for thw various argument options for rrule ?

Thanks once again.

**Comment by tplaner** [comment]
Correct, it includes every example from the spec RFC5545: https://datatracker.ietf.org/doc/html/rfc5545#section-3.8.5

**Comment by marcoczen** [comment]
Thanks. Closed.

**Comment by boryn** [comment]
Hi! I believe adding information about

```php
$when = new When();
$when->RFC5545_COMPLIANT = When::IGNORE;
```

or 

```php
->bymonthday(-1)
```

could be very helpful. 

Also, maybe listing all the methods with little comment could be beneficial. For example what does `wkst()` mean? I was looking for the "every second Thursday" rule in the tests and I finally found `interval()` but that would be indeed great to see some more examples directly in the README.

**Comment by marcoczen** [comment]
Thanks.  

> Hi! I believe adding information about
> 
> ```
> $when = new When();
> $when->RFC5545_COMPLIANT = When::IGNORE;
> ```
> 
> or
> 
> ```
> ->bymonthday(-1)
> ```
> 
> could be very helpful.
> 
> Also, maybe listing all the methods with little comment could be beneficial. For example what does `wkst()` mean? I was looking for the "every second Thursday" rule in the tests and I finally found `interval()` but that would be indeed great to see some more examples directly in the README.

**Comment by tplaner** [comment]
@marcoczen updated the readme with more examples/information. Thanks for the suggestions.

**Comment by marcoczen** [comment]
Thanks.
