### ISSUE TITLE
Is 0 allowed in the BYDAY rule with the day name?

### ISSUE THREAD

**Issue by boryn** [tplaner/When#84]
The RRule `"FREQ=WEEKLY;BYDAY=TU"` internally produces `$r->bydays` with `createDaysList()` as:

```
array:1 [
  0 => "0tu"
]
```
Is it a proper behaviour? I ask because after converting with `toRrule()` we get ``"FREQ=WEEKLY;BYDAY=0tu"`` which is not accepted as valid with `->rrule()`.

Should the fix be made at the level of `createDaysList()` or it would be fine just to strip the leading 0 in the `toRrule()`?

**Comment by tplaner** [comment]
Thanks for the report.

I see nothing in the spec about not allowing 0, I've gone ahead and allowed it in the validator.
