### ISSUE TITLE
Edge case producing results beyond UNTIL

### ISSUE THREAD

**Issue by boryn** [tplaner/When#85]
Every tuesday at 18:00:00 with start at "2021-08-31 **09:00:00**" and until at "2021-08-31 **17:00:00**" 
produces the event at "2021-08-31 **18:00:00**" but IMHO it should not.

```php
$r = new When();
$r->startDate(new \DateTime("2021-08-31 09:00:00"))
  ->rrule("FREQ=WEEKLY;BYDAY=TU;BYHOUR=18;BYMINUTE=0;BYSECOND=0")
  ->until(new \DateTime("2021-08-31 17:00:00"))
  ->generateOccurrences();

print_r($r->occurrences);
```

**Comment by tplaner** [comment]
Nice find, I went ahead and fixed this in [v3.1.3](https://github.com/tplaner/When/tree/v3.1.3).
