### ISSUE TITLE
Front-end design for user input

### ISSUE THREAD

**Issue by boryn** [tplaner/When#87]
(Actually, it's not an issue, more a discussion topic)

Do you have any tested and proven front-end design for accepting the user input? I'm looking at the Google Calendar interface and it seems quite good. Do you have any other ideas / recommendations?

![image](https://user-images.githubusercontent.com/807297/131790071-d0c95a85-10b1-4046-a842-01debfcde4de.png)

![image](https://user-images.githubusercontent.com/807297/131789950-bab9cdc4-9554-45e2-ac46-77fdf478be35.png)

![image](https://user-images.githubusercontent.com/807297/131790021-8759a41f-1cf0-45a8-89c2-15f6e35558c3.png)

**Comment by PrplHaz4** [comment]
In my experience this is a fairly complex control to implement, so if you don't need the full flexibility, you may benefit from a more simple interface.

That being said - Google Calendar and Outlook interfaces for recurrence are fairly similar, and what I've used in the past as the "standard" reference.

**Comment by boryn** [comment]
I have just found this library which could be quite helpful in implementing front-end 
(nice thing is that it "translates" on the spot user input directly to RRule):

http://jakubroztocil.github.io/rrule/

**Comment by tplaner** [comment]
This is a good question and from my research, I have not found a great solution. Most UI's are limiting in some capacity to what the library is capable of.

With that said, for Rindle's recurring scheduler we actually utilize the above [JavaScript rrule library](http://jakubroztocil.github.io/rrule/) and accept text input that we convert into a rrule for use on the backend utilizing When:

<img src="https://user-images.githubusercontent.com/50652/132047100-8bc503cc-35a1-4038-a2ff-2e70065ace44.png" alt="Rindle Picker" width=500 />

This covers the majority of common use cases and is relatively easy for our users. However, it is not perfect and does not 100% handle every use case.

I'd love to add the ability to parse text string out in Rindle at some point.

**Comment by boryn** [comment]
Thank you for your thoughts on this subject! It's not my skill set, but that would be nice to have some vue component for this :)

Outlook has a really clean interface, we would go for something similar, using tabs for choosing day/week/month cycle.

**Comment by boryn** [comment]
@tplaner maybe it would be good to create the separate Discussion tab in the project?

**Comment by tplaner** [comment]
I've enabled the discussions tab.
