### ISSUE TITLE
`$startDate` and `$endDate` could be accepted as `instanceof \DateTimeImmutable`

### ISSUE THREAD

**Issue by boryn** [tplaner/When#88]
IMHO `$startDate` and `$endDate` could/should be accepted as well as the instances of `DateTimeImmutable`.

PS. Very easy to implement at `dateTimeObject()` but was not sure about `occursOn()` and that's why I have not prepared the PR.

**Comment by tplaner** [comment]
Take a look at the last commit: https://github.com/tplaner/When/commit/84d280a49f6d3acc5515b9b3436f42b5b710a54e
