### ISSUE TITLE
Unable to understand 'BYSETPOS' in the Docs

### ISSUE THREAD

**Issue by marcoczen** [tplaner/When#89]
Guys, 

With  reference to

```  rrule("FREQ=MONTHLY;INTERVAL=1;BYSETPOS=-1;BYDAY=MO,TU,WE,TH,FR;BYMONTHDAY=13,14,15;COUNT=12")   ```

I just cant seem to understand the purpose of 'bysetpos' ? 
Anybody here can explain it ?

Thanks in advance ...

**Comment by boryn** [comment]
Hi @marcoczen!

With the example of `"FREQ=MONTHLY;INTERVAL=1;BYSETPOS=-1;BYDAY=MO,TU,WE,TH,FR;BYMONTHDAY=26,27,28,29,30,31;COUNT=12"`
 you have a set of occurences falling at 26-31 of the month and only on MO,TU,WE,TH,FR. 

BYSETPOS is not a rule by itself, actually it limits the rule. It means take the n-th instance from the calculated instances corresponding to the rest of the rule. So in our case it means take the last day at the end of the month of the working days.

Hope it clarifies :)

**Comment by marcoczen** [comment]
Hi @boryn ,

> BYSETPOS is not a rule by itself, actually it limits the rule.

Noted ...

**Comment by marcoczen** [comment]
For the next noob ...
