### ISSUE TITLE
weekly every 2 or 3 or 4th week on mo, tu, we not possible?

### ISSUE THREAD

**Issue by CLutz86** [tplaner/When#91]
hi there,

I'm trying to get dates of the following scenario, but always getting "undefined index" in When.php line 677.
`$when->startDate(now())->freq("weekly")->interval(3)->byday('mo,tu,we')`

This is working perfectly, but if I choose interval > 1 then it doesn't work 
`$when->startDate(now())->freq("weekly")->interval(1)->byday('mo,tu,we')` 

thanks in advance

**Comment by tplaner** [comment]
Make sure you have the latest version of When installed (v3.1.5).

I tested with this code, and it seems to work fine:

```php
use Carbon\Carbon;
use When\When;

function now($tz = null)
{
    return Carbon::now($tz);
}

$when = new When();
$when->RFC5545_COMPLIANT = When::IGNORE;

$when->startDate(now())->freq("weekly")->interval(3)->byday('mo,tu,we');

$when->generateOccurrences();

print_r($when->occurrences);
```

**Comment by CLutz86** [comment]
thx. Works like a charm :)
