### ISSUE TITLE
Repeat dates weekly with more one day on week

### ISSUE THREAD

**Issue by filipemansano** [tplaner/When#92]
I tried to create the following occurrence 
"Repeat every 2 week on Sunday and Monday"

```php
$r = new \When\When();
$r->RFC5545_COMPLIANT = \When\When::IGNORE;
$r->startDate(new DateTime("20220101"))
   ->freq("weekly")
   ->interval(2)
   ->byday("su,mo")
   ->until(new DateTime("20220131"))
   ->generateOccurrences();

print_r($r->occurrences);
```

Output:
```
Array
(
    [0] => 2022-01-02
    [1] => 2022-01-10
    [2] => 2022-01-16
    [3] => 2022-01-24
    [4] => 2022-01-30
)
```

Expected:
```
Array
(
    [0] => 2022-01-02
    [1] => 2022-01-03
    [2] => 2022-01-16
    [3] => 2022-01-17
    [4] => 2022-01-30
    [4] => 2022-01-31
)
```

Visual Results
| Output   |      Expected      |
|----------|-------------|
|  ![DeepinScreenshot_select-area_20211030015301](https://user-images.githubusercontent.com/6247393/139520691-57fc0845-d140-4c3a-bfda-03dd16f6c79f.png) | ![DeepinScreenshot_select-area_20211030015203](https://user-images.githubusercontent.com/6247393/139520702-dfec3bb0-9d35-4ddf-95ce-fb175f145c25.png) |

exists any way to interval affect only week and not days in week?

**Comment by tplaner** [comment]
Hi @filipemansano,

Sorry for the delayed response, I honestly missed this question, this is as expected according to the spec, you can get it to do what you want if you add `wkst('su')` and setting the first occurrence to the first Sunday, if not it will be skipped:

```
$r->startDate(new DateTime("20220102"))
    ->wkst('su')
    ->freq("weekly")
    ->interval(2)
    ->byday("su,mo")
    ->until(new DateTime("20220131"))
    ->generateOccurrences();
```

I checked with a few other rrule generators and they all had consistent behavior with your original rrule.

The above rule produces the results you desire.

Hope this helps.
