### ISSUE TITLE
Validate a rrule string

### ISSUE THREAD

**Issue by coxy17** [tplaner/When#98]
Hi

I wondered what is the best approach to validate the structure of a rrule string? i ask as i will save strings in forms from user inputs so need to make sure they are formatted correctly too.

e.g. 
`FREQ=DAILY;INTERVAL=1;UNTIL=20251130T133000`

So if the string was missing a required e.g. FREQ or there is a misspelt word. Is there a way to catch an error if checking via When?

**Comment by pluk77** [comment]
Perhaps pass the string to the rrrule() function and check if it throws any exceptions?

**Comment by coxy17** [comment]
I have tested and it works ok using both approaches using form fields for date etc and error checking (exceptions). Thanks
